name: NPM Test on Main

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test || true
